---
name: Cdk Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
  TZ: Asia/Singapore

jobs:
  bootstrap-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set shell options
        run: set -euxo pipefail

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_OIDC_ROLE_ARN }}
          role-session-name: aws-oidc-${{ github.repository.name }}-${{ github.run_id }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - uses: actions/setup-node@v4
        with:
          node-version: '22.15.1'

      - name: Install aws-cdk 
        run: sudo npm install -g aws-cdk

      - name: cdk bootstrap
        run: make bootstrap

      - name: cdk deploy
        run: make deploy
